# Alla personer med wikidata-URI som förekommer i materialet.
# wdt:P31 (instance of)
# wd:Q5 (human)

PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>        
PREFIX wd: <http://www.wikidata.org/entity/>

SELECT ?qnumber 
WHERE {
      ?person wdt:P31 wd:Q5 .
      BIND (replace(str(?person), "http://www.wikidata.org/wiki/ ) ?qnumber as 
FILTER(regex(str(?person), "www.wikidata.org" ) )
}
